Description: >
  This template sets up the full stack with continuous deployment for 
  the auth service. 

Parameters:
  JwtPrivateKey:
    Type: String
    Description: Shared private key used between services for token signing.

  ApiAuthUsername:
    Type: String
    Description: Username used for basic authentication when accessing service apis.

  ApiAuthPassword:
    Type: String
    Description: Password used for basic authentication when accessing service apis.

  GitHubUser:
    Type: String
    Description: Username on GitHub.

  GitHubRepo:
    Type: String
    Description: Repo name of the auth service.

  GitHubBranch:
    Type: String
    Description: The branch of the repo to continuously deploy.

  GitHubToken:
    Type: String
    Description: >
      Token for the user specified above. (https://github.com/settings/tokens)


Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      JwtPrivateKey:
        default: "Jwt Private Key"
      ApiAuthUsername:
        default: "Api Username"
      ApiAuthPassword:
        default: "Api Password"
      GitHubUser:
        default: "Github User"
      GitHubRepo:
        default: "Github Repo"
      GitHubBranch:
        default: "Github Branch"
      GitHubToken:
        default: "Personal Access Token"
    ParameterGroups:
      - Label:
          default: GitHub Configuration
        Parameters:
          - JwtPrivateKey
          - ApiAuthUsername
          - ApiAuthPassword
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken


Resources:
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/compeat/auth-ecs-cluster.yaml
      Parameters:
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/compeat/auth-deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        LoadBalancerTargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        ServiceRepository: !GetAtt Service.Outputs.Repository
        ServiceStackName: !GetAtt Service.Outputs.StackName
        TemplateBucket: auth-service-deployment
        JwtPrivateKey: !Ref JwtPrivateKey
        ApiAuthUsername: !Ref ApiAuthUsername
        ApiAuthPassword: !Ref ApiAuthPassword

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/compeat/auth-load-balancer.yaml
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/compeat/auth-service.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        LoadBalancerTargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        JwtPrivateKey: !Ref JwtPrivateKey
        ApiAuthUsername: !Ref ApiAuthUsername
        ApiAuthPassword: !Ref ApiAuthPassword

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/compeat/auth-vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24


Outputs:
  ServiceUrl:
    Description: The auth service.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl

  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
